---
user: TEST
group: TEST

install_dir: /opt/TEST/TEST
TEST_home: /opt/TEST/TEST/base

db_el_vendor: postgresql
db_el_tablespace: ctl
db_el_tablespace_index: ctlidx
db_el_jdbc_driver: /usr/share/java/postgresql-jdbc.jar
db_el_properties: 
db_el_type: 
db_el_port: "{{ postgresql_server_port }}"
db_el_name: TEST
...
