{
 "title": "System monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "drinstance", "label": "Data Refinery instances", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"[[drinstance]]\"}",
     "legendFormat": "Total disk: instance={{instance}}, device={{device}}, mount point={{mountpoint}}"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"[[drinstance]]\"}",
     "legendFormat": "Available disk: instance={{instance}}, device={{device}}, mount point={{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"[[drinstance]]\"} - node_filesystem_avail_bytes{instance=~\"[[drinstance]]\"}",
     "legendFormat": "Free disk: instance={{instance}}, device={{device}}, mount point={{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{ mode=\"idle\", instance=~\"[[drinstance]]\"}[120s])) * 100)",
     "legendFormat": "instance={{instance}},"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"[[drinstance]]\"}[120s])",
     "legendFormat": " Incoming network: instance={{instance}}, device={{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"[[drinstance]]\"}[120s])",
     "legendFormat": "Outgoing network: instance={{instance}}, device={{device}} "
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"[[drinstance]]\"}",
     "legendFormat": "Total memory: instance={{instance}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"[[drinstance]]\"} - node_memory_MemFree_bytes{instance=~\"[[drinstance]]\"} - node_memory_Cached_bytes{instance=~\"[[drinstance]]\"} - node_memory_Buffers_bytes{instance=~\"[[drinstance]]\"}",
     "legendFormat": "Use memory: instance={{instance}}"
    }
   ]
  }
 ]
}