{
 "title": "5G NCHF Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{instance=\"$instance\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",area=\"heap\"})*100/sum(jvm_memory_max_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\",area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\",area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\",area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\",area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Create Requests (count)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata\",status=\"201\"}",
     "legendFormat": "status 201"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata\",status=\"404\"}",
     "legendFormat": "status 404"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata\",status=\"500\"}",
     "legendFormat": "status 500"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata\",status!~\"201|404|500\"}",
     "legendFormat": "others"
    }
   ]
  },
  {
   "title": "Update Requests (count)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/update\",status=\"200\"}",
     "legendFormat": "status 200"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/update\",status=\"404\"}",
     "legendFormat": "status 404"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/update\",status=\"500\"}",
     "legendFormat": "status 500"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/update\",status!~\"200|404|500\"}"
    }
   ]
  },
  {
   "title": "Release Requests (count)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/release\",status=\"204\"}",
     "legendFormat": "status 204 "
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/release\",status=\"404\"}",
     "legendFormat": "status 404"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/release\",status=\"500\"}",
     "legendFormat": "status 500"
    },
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/release\",status!~\"204|404|500\"}",
     "legendFormat": "others"
    }
   ]
  },
  {
   "title": "Create Request (Live)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata\",status=\"201\"}[1m])",
     "legendFormat": "status 201"
    },
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata\",status=\"404\"}[1m])",
     "legendFormat": "status 400"
    },
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata\",status=\"500\"}[1m])",
     "legendFormat": "status 500"
    },
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata\",status!~\"201|500|404\"}[1m])",
     "legendFormat": "others"
    }
   ]
  },
  {
   "title": "Update Requests (live)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/update\",status=\"200\"}[1m])",
     "legendFormat": "status 200"
    },
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/update\",status=\"404\"}[1m])",
     "legendFormat": "status 404"
    },
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/update\",status=\"500\"}[1m])",
     "legendFormat": "status 500"
    },
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/update\",status!~\"200|404|500\"}[1m])",
     "legendFormat": "others"
    }
   ]
  },
  {
   "title": "Release Requests (live)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/release\",status=\"204\"}[1m])",
     "legendFormat": "status 204 "
    },
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/release\",status=\"404\"}[1m])",
     "legendFormat": "status 404"
    },
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/release\",status=\"500\"}[1m])",
     "legendFormat": "status 500"
    },
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\",uri=\"/nchf-convergedcharging/v2/chargingdata/{ChargingDataRef}/release\",status!~\"204|404|500\"}[1m])",
     "legendFormat": "others"
    }
   ]
  }
 ]
}