---
product_fqdn: "{{ inventory_hostname }}"


validity_days: 3650
el_ui_user: TEST
el_ui_group: TEST

keystore_password: "KeyStorePassword"
keystore_file: "{{ product_install_dir }}/{{ keystore_file_name }}"
# Key password should match keystore file password
# Otherwise "java.security.UnrecoverableKeyException: Cannot recover key" exception will be thrown by application
# https://stackoverflow.com/questions/15967650/caused-by-java-security-unrecoverablekeyexception-cannot-recover-key
# http://karim-ouda.blogspot.bg/2010/07/errors-solutions-5.html
# https://stackoverflow.com/questions/14606837/cannot-recover-key
certificate_password: "{{ keystore_password }}"
truststore_file: "{{ product_install_dir }}/{{ truststore_file_name }}"
truststore_password: "TruststorePassword"
start_wait_timeout: "30"
kc_fqdn: "{{ inventory_hostname }}"
kc_https_port: 8666
kc_https_url: "https://{{ kc_fqdn }}:{{ kc_https_port }}/auth"
responses_organization: "TEST"
responses_correct: "yes"
kc_realm_name: "TEST"
kc_realm_admin_user: "realmadmin"
kc_realm_admin_password: "realmadmin"
kc_certificate_name: "keycloak-certificate"
kc_ssl_certificate_file: "{{ ansible_dir }}/{{ kc_certificate_name }}"
kc_client_protocolMappers:
  - name: "username"
    protocol: "openid-connect"
    protocolMapper: "oidc-usermodel-property-mapper"
    consentText: "${username}"
    consentRequired: true
    config:
      access.token.claim: "true"
      claim.name: "preferred_username"
      id.token.claim: "true"
      jsonType.label: "String"
      user.attribute: "username"
      userinfo.token.claim: "true"
  - name: "email"
    protocol: "openid-connect"
    protocolMapper: "oidc-usermodel-property-mapper"
    consentText: "${email}"
    consentRequired: true
    config:
      access.token.claim: "true"
      claim.name: "email"
      id.token.claim: "true"
      jsonType.label: "String"
      user.attribute: "email"
      userinfo.token.claim: "true"
  - name: "full name"
    protocol: "openid-connect"
    protocolMapper: "oidc-full-name-mapper"
    consentText: "${fullName}"
    consentRequired: true
    config:
      access.token.claim: "true"
      id.token.claim: "true"
      userinfo.token.claim: "true"
