---

# Execute TEST_drop_db.sql 
- name: drop TEST tables
  shell: ". {{ TEST_home }}/bin/db_tools.sh && init_db EL
                && run_db_script {{ TEST_home }}/sql/TEST/TEST_drop_db.sql {{ TEST_home }}/log/TEST_drop_db.sql.log"
  register: script_result_drop_TEST_tables

# Fail the execution if script executed with error
- name: fail when executing TEST_drop_db.sql script has an error
  fail: msg="Error found when executing script"
  when: >
   ( script_result_drop_TEST_tables.stderr is defined ) 
   and ( "error:" in item | lower )
   or ( "could not connect" in item | lower )
  with_items: "{{ script_result_drop_TEST_tables.stderr.split('\n') }}"
   
# Execute lookup_server_delete.sql 
- name: drop lookupserver tables
  shell: ". {{ TEST_home }}/bin/db_tools.sh && init_db LS
                && run_db_script {{ TEST_home }}/sql/lookupserver/lookup_server_delete.sql {{ TEST_home }}/log/lookup_server_delete.sql.log"
  register: script_result_drop_ls_tables

# Fail the execution if script executed with error
- name: fail when executing lookup_server_delete.sql script has an error
  fail: msg="Error found when executing script"
  when: >
   ( script_result_drop_ls_tables.stderr is defined ) 
   and ( "error:" in item | lower )
   or ( "could not connect" in item | lower )
  with_items: "{{ script_result_drop_ls_tables.stderr.split('\n') }}"
  
# Execute txe_drop_schema.sql 
- name: drop mcp tables
  shell: ". {{ TEST_home }}/bin/db_tools.sh && init_db MCP
                && run_db_script {{ TEST_home }}/sql/mcp/txe_drop_schema.sql {{ TEST_home }}/log/txe_drop_schema.sql.log"
  register: script_result_drop_mcp_tables

# Fail the execution if script executed with error
- name: fail when executing txe_drop_schema.sql script has an error
  fail: msg="Error found when executing script"
  when: >
   ( script_result_drop_mcp_tables.stderr is defined ) 
   and ( "error:" in item | lower )
   or ( "could not connect" in item | lower )
  with_items: "{{ script_result_drop_mcp_tables.stderr.split('\n') }}"
    
...