---
charging_ip: "{{ ansible_local.addresses.all.charg_ip }}"
group_name: "{{ group_names | difference('vdu-cgf') | first }}"
aspect_index: "{{ group_name.split('-')[-1]|int }}"
node0: "{{ (aspect_index|int + 1) * 2 - 2 }}"
node1: "{{ (aspect_index|int + 1) * 2 - 1 }}"
admintools_protocol: "https"
monitor_timesten: "{{ vnf_context_data.stack_params.cbam.extensions.cgf_enable_timesten }}"
gtp_install_flag: false

host_type: cgf
processing_type: offline
ip_groups:
  - ha_interface: "{{ ansible_local.interfaces.devices.oam_interface }}"
    ha_vrid: 131
    ha_vip: "{{ cgf_oam_vip_list[aspect_index|int].ip }}"
    ip0: "{{ cgf_oam_ip_list[node0|int].ip }}"
    ip1: "{{ cgf_oam_ip_list[node1|int].ip }}"
    netmask: "{{ vnf_context_data.stack_params.cbam.extensions.oam_network_netmask }}"
  - ha_interface: "{{ ansible_local.interfaces.devices.charg_interface }}"
    ha_vrid: 132
    ha_vip: "{{ cgf_charg_vip_list[aspect_index|int].ip }}"
    ip0: "{{ cgf_charg_ip_list[node0|int].ip }}"
    ip1: "{{ cgf_charg_ip_list[node1|int].ip }}"
    netmask: "{{ vnf_context_data.stack_params.cbam.extensions.charging_network_netmask }}"
  - ha_interface: "{{ ansible_local.interfaces.devices.bill_interface }}"
    ha_vrid: 133
    ha_vip: "{{ cgf_bill_vip_list[aspect_index|int].ip }}"
    ip0: "{{ cgf_bill_ip_list[node0|int].ip }}"
    ip1: "{{ cgf_bill_ip_list[node1|int].ip }}"
    netmask: "{{ vnf_context_data.stack_params.cbam.extensions.billing_network_netmask }}"

ha_mode: "active-passive"


cinder_volumes:
  - name: data
    filesystem: xfs
    label: data
    opts: '-b size=4096 -L data'
    device: "/dev/disk/by-id/virtio-{{ ansible_local['disks']['cgf']['data_mount_id'][0:20] }}"
    mount_point: /opt/TEST/TEST/data
    mount_point_dash: opt-TEST-TEST-data
    owner: TEST
    group: TEST
    mode: "0700"
  - name: storage
    filesystem: xfs
    label: storage
    opts: '-b size=4096 -L storage'
    device: "/dev/disk/by-id/virtio-{{ ansible_local['disks']['cgf']['storage_mount_id'][0:20] }}"
    mount_point: /opt/TEST/TEST/storage
    mount_point_dash: opt-TEST-TEST-storage
    owner: TEST
    group: TEST
    mode: "0700"
  - name: offline
    filesystem: xfs
    label: offline
    opts: '-b size=4096 -L offline'
    device: "/dev/disk/by-id/virtio-{{ ansible_local['disks']['cgf']['offline_mount_id'][0:20] }}"
    mount_point: /opt/TEST/TEST/offline
    mount_point_dash: opt-TEST-TEST-offline
    owner: TEST
    group: TEST
    mode: "0700"
  - name: control
    filesystem: xfs
    label: control
    opts: '-b size=4096 -L control'
#    device: "/dev/disk/by-id/virtio-{{ vnf_context_data['resource_model']['resources']['cgf_aspect_group']['resources'][inventory_hostname.split('-')[4]]['resources']['data_volume_6']['attributes']['id'][0:20] }}"
    device: "/dev/disk/by-id/virtio-{{ ansible_local['disks']['cgf']['control_mount_id'][0:20] }}"
    mount_point: /opt/TEST/TEST/control
    mount_point_dash: opt-TEST-TEST-control
    owner: TEST
    group: TEST
    mode: "0700"
nfs_mounts:
