- debug: msg="Wait for hosts up and ready for login to {{ ansible_ssh_host }}"

- name: Wait for the nodes to wake up
  wait_for: host={{ ansible_ssh_host | default(inventory_hostname) }} port=22 timeout=120 state=started
  become: no

- name: pause
  pause: seconds=15