---
- name: preparations
  hosts: ui_aspect_group.0.server
  gather_facts: no
  tasks:
    - name: Update some values in runplaybook.sh for the 2nd Ansible run
      replace:
        path: '{{ inventory_dir }}/runplaybook.sh'
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      delegate_to: localhost
      with_items:
        - { regexp: "std.out", replace: "std_check.out" }
        - { regexp: "ha.yml", replace: "check_faulty_ha_node.yaml" }
        - { regexp: "-vvvv", replace: "{{ vnf_context_data.stack_params.cbam.extensions.ansible_verbosity }}" }
        - { regexp: "ansible_inventory.py", replace: "inventory" }
      when: expected_ha_role is not defined

    - name: Create ansible.cfg from template
      template: src="{{ playbook_dir }}/templates/ansible.cfg.j2" dest="{{ inventory_dir }}/ansible.cfg"
      delegate_to: localhost

    - name: make inventory from template
      template: src="{{ playbook_dir }}/templates/inventory.j2" dest="{{ inventory_dir }}/inventory"
      delegate_to: localhost

    - name: rerun the script for ansible
      local_action: script {{ inventory_dir }}/runplaybook.sh
